// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { migrationDatabaseUrl } from "./lib/database-url";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Supabase: Prisma CLI uses DIRECT_URL (session pooler :5432 or db.*.supabase.co).
    // SSL + connect_timeout are added automatically — required for Prisma migrate.
    url: migrationDatabaseUrl(),
  },
});
